<template>
  <div>
    <tokenbar :teams="teams" />
    <main id="map" class="map"></main>
    <new-entry-button />
  </div>
</template>

<script>
import {mapGetters} from 'vuex'
import L from 'leaflet'
import Tokenbar from '@/components/Tokenbar'
import NewEntryButton from '@/components/NewEntryButton'

export default {
  name: 'MapPage',
  components: {
    Tokenbar,
    NewEntryButton
  },
  data () {
    return {
      map: null
    }
  },
  computed: {
    ...mapGetters({
      teams: 'tokenTeams'
    })
  },
  methods: {
    drawWaypoints () {
      this.teams.forEach(team => {
        team.waypoints.forEach(waypoint => {
          let marker = L.marker(waypoint.location, {
            icon: L.divIcon({
              html: '<i class="clear fa fa-flag fa-2x" style="color: ' + team.color + ';" />',
              iconSize: [24, 24],
              iconAnchor: [0, 24],
              popupAnchor: [3, -23]
            })
          }).addTo(this.map)

          marker.bindPopup(waypoint.time)
        })
      })
    },
    onMapClick (e) {
      console.log(e.latlng)
    }
  },
  mounted () {
    let tiles = L.tileLayer('/static/map/{z}/{x}/{y}.png', {tms: true, opacity: 1, attribution: 'Generated by <a href="http://www.klokan.cz/projects/gdal2tiles/">GDAL2Tiles</a>, Copyright &copy; 2008 <a href="http://www.klokan.cz/">Klokan Petr Pridal</a>,  <a href="http://www.gdal.org/">GDAL</a> &amp; <a href="http://www.osgeo.org/">OSGeo</a> <a href="http://code.google.com/soc/">GSoC</a>'})

    let map = L.map('map', {
      center: [-32.3514860545, 150.263529391],
      zoom: 14,
      minZoom: 13,
      maxZoom: 15,
      maxBounds: L.latLngBounds(
        L.latLng(-32.3031306355766, 150.22524833679202),
        L.latLng(-32.3993129737779, 150.30159473419192)
      ),
      maxBoundsViscosity: 1.0,
      layers: [tiles]
    })

    this.map = map

    this.drawWaypoints()

    this.map.on('click', this.onMapClick)
  }
}
</script>

<style>

</style>
