const state = {
  map: {
    path: '/static/map/{z}/{x}/{y}.png',
    opacity: 1,
    attribution: 'Generated by <a href="http://www.klokan.cz/projects/gdal2tiles/">GDAL2Tiles</a>, Copyright &copy; 2008 <a href="http://www.klokan.cz/">Klokan Petr Pridal</a>,  <a href="http://www.gdal.org/">GDAL</a> &amp; <a href="http://www.osgeo.org/">OSGeo</a> <a href="http://code.google.com/soc/">GSoC</a>',
    options: {
      center: [-32.3514860545, 150.263529391],
      zoom: 14,
      minZoom: 13,
      maxZoom: 15,
      maxBounds: L.latLngBounds(
        L.latLng(-32.3031306355766, 150.22524833679202),
        L.latLng(-32.3993129737779, 150.30159473419192)
      ),
      maxBoundsViscosity: 1.0
    }
  }
}

const getters = {
  getMap: (state) => {
    return state.map
  }
}

const actions = {

}

const mutations = {

}

export default {
  namespaced: false,
  state,
  getters,
  actions,
  mutations
}
